### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by dreaddr** [Mamiglia/Reddit-Wallpaper#1]
I just wanted to ask if there would be support for Linux? In the future or if it supports Linux already.

**Comment by Mamiglia** [comment]
Technically it could be adapted, and it would be fairly easy. The only parts to be modified are in the class SetNewWallpaper.java and the installer. The problem with linux is that it has many Desktop Manager (KDE, XFCE, GNOME.. etc) and each of them has a different way to apply a wallpaper. For instance if you read the code in SetNewWallpaper.java you would see a method to apply a wallpaper in XFCE (as this was the VM's DE I developed on).

I plan to add such feature in the future

**Comment by dreaddr** [comment]
Yep, this is the exact same issue I'm facing with `wallpaper-reddit` package as I use the Deepin DE, and that isn't supported by that package. Hope the best in adding these features, you can close this issue if you so wish.

**Comment by HarshaVardhanNakkina** [comment]
@dreaddr you can use [styli.sh](https://github.com/thevinter/styli.sh) for linux

**Comment by dreaddr** [comment]
Thanks @HarshaVardhanNakkina
