### ISSUE TITLE
The NSFW slider position is not save and repositioning itself in the default position

### ISSUE THREAD

**Issue by Sky-NiniKo** [Mamiglia/Reddit-Wallpaper#10]
How to reproduce it:
- Change the position of the slider (e.g. Never)
- Click on the Apply button
- Close the settings window
- Reopen the settings window

**Comment by Mamiglia** [comment]
I forgot to implement this! Thanks for noticing, the commit fixes this, in a couple of days I'll release the 1.1.1 version (so that we can also test the auto update thing :)
