### ISSUE TITLE
Wallpaper retrieval suggestions

### ISSUE THREAD

**Issue by kentrospections** [Mamiglia/Reddit-Wallpaper#21]
My internet is not that great all the time, so sometimes I catch Reddit-Wallpaper just not changing the wallpaper at all. Using `Change Now` doesn't work in this case: the log always says it's pressed too early. Maybe a timeout and/or brute force change wallpaper option would be great to mitigate this.

**Comment by Mamiglia** [comment]
I still haven't tested RW with a bad internet connection could you copy-paste the log here? 
In any case: while I do like the idea of a timeout, I don't think that a button that forcibly shuts down the actual process is a good idea (also because I think it would be abused by impatient users)

**Comment by kentrospections** [comment]
Unfortunately I don't have a log to paste (I've restarted RW since) but I specifically remember RW getting stuck in `INFO: Search Query is:`.

I haven't thought about abuse for forcing the process, that makes sense. But maybe it would be still be viable with a timeout?

**Comment by Mamiglia** [comment]
Well, if that was the log info than it must be something more than just the internet connection. Usually after `INFO: Search Query is:` there's is a URL representing the query, and that's generated offline. If it was void afterwards then it means that there's a bug somewhere that interrupts the esxecution and doesn't generate the query

**Comment by kentrospections** [comment]
Oh, there is a link, I just didn't include it for privacy reasons.

**Comment by Mamiglia** [comment]
Oh, it's fair. Will try to look further into the issue

**Comment by Mamiglia** [comment]
I've tested the implementation of a timeout, but such behaviour is already present in the standard http protocol, and as such the standard http timeout would clash with an external timeout. 

As such this feature won't be implemented
