### ISSUE TITLE
GUI Corruption

### ISSUE THREAD

**Issue by SpaceArchMage** [Mamiglia/Reddit-Wallpaper#23]
Hi, Well something is not right with the GUI rendering

![Screenshot 2022-02-28 194713](https://user-images.githubusercontent.com/11452275/156019066-604f059f-f4cc-4f62-a1ba-9b25fe2823be.png)

Environment:
Win 10 21H2
RTX 3080
Nvidia Driver Version: 511.79 DCH
Resolution: 2560*1080

**Comment by Mamiglia** [comment]
Well, this is weird. I believe this is fault of java swing and/or FlatLaf. I don't think I have any way to fix this. Does this happen often? Is it fixed by closing and reopening it?

**Comment by SpaceArchMage** [comment]
it happens always, but I found the culprit, it's the combination of GeForce experience overlay (Detects the app as a 3D game I guess) and windows dark mode, weirdly it's fine with windows light colors. 

anyways it's not a big deal, thanks for replying.
