### ISSUE TITLE
Something went wrong: couldn't download or select a new wallpaper

### ISSUE THREAD

**Issue by WhatIsLove47-ru** [Mamiglia/Reddit-Wallpaper#25]
I've this problem after Java got an update, I guess.
I often switch the resolutions of my two screens.
I hope log will help.
[out.log](https://github.com/Mamiglia/Reddit-Wallpaper/files/8641748/out.log)

**Comment by aTomicTurnip** [comment]
Same here

**Comment by Mamiglia** [comment]
Hopefully the current release fixes this issue. Until then I'm gonna close this Issue
