### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by TriforceofWisdom** [Mamiglia/Reddit-Wallpaper#28]
This is quite simple, all I'm thinking is a short fade between each wallpaper to make it look a little nicer when it changes.

**Comment by Mamiglia** [comment]
Unfortunately this is really not possible, as the transition is handled by
Windows, not RW. As far as I know Windows doesn't support yet any
transition animation when changing wallpaper

Il mar 15 ago 2023, 01:28 TriforceofWisdom ***@***.***> ha
scritto:

**Comment by Masamune3210** [comment]
Maybe write the wallpapers into a folder and have windows use it's built in support for slideshows as wallpapers?
