### ISSUE TITLE
Changing saved wallpaper folder is not honoured

### ISSUE THREAD

**Issue by Masamune3210** [Mamiglia/Reddit-Wallpaper#5]
Changed the wallpaper folder but the wallpapers are still being saved in the default location

**Comment by Mamiglia** [comment]
Did you press the "Apply" button after changing the wallpaper folder?

**Comment by Masamune3210** [comment]
Indeed

**Comment by Mamiglia** [comment]
Can you help me replicating this issue by telling me exactly what you did before the bug? If possible, can you paste here the log?

**Comment by Masamune3210** [comment]
Will try to recreate and get the log when I get back to my comp in a couple hours

**Comment by Masamune3210** [comment]
Recreated the issue, the setting isnt honoured until the program is completely closed from the tray and reloaded. Log showed nothing other than the source of the wallpaper unless you are talking about some log other than the one in the program window

**Comment by Mamiglia** [comment]
Thanks to you I have recreated the issue and yes, it appears that **changing the wallpaper destination folder doesn't take effect until the program is restarted.** 

I will solve this bug before the next release

**Comment by Mamiglia** [comment]
The issue should be fixed with this commit
