### ISSUE TITLE
Change the background every month

### ISSUE THREAD

**Issue by Sky-NiniKo** [Mamiglia/Reddit-Wallpaper#7]
With the current implementation the timer for the wallpaper change is reset at each startup.
Are there any plans to solve this problem?
For example by saving the time of the last wallpaper change and see how long ago it was.

**Comment by Mamiglia** [comment]
I've never considered this scenario. Actually the tool changes the wallpaper immidiately as it's started (when the PC is started). The fact is that this tool weights around ~150MB on your RAM, and if you want it to change the wallpaper once every month it becomes quite "heavy" considering how little it would be used. 

Anyway I think I'm gonna implement this feature anyway, and the way you suggested it looks optimal

**Comment by Sky-NiniKo** [comment]
Thank you for your informative answer. I will let you close the issue if you wish.

**Comment by Sky-NiniKo** [comment]
I don't know what is taking up the RAM but if it is the GUI. You can do a services on windows ( services.msc ), a daemon on linux and I don't know about mac but there must be something similar. I think it's hard to do and cross-platform must be harder to maintain but it's just an idea like that.

**Comment by Mamiglia** [comment]
With the [last commit](https://github.com/Mamiglia/Reddit-Wallpaper/commit/7ce0a7b05f236604fc666b047fa87a04a7801871) the issue was fixed, it will be included in the next release. The thing about windows services is really interesting, I will look further into it

**Comment by Sky-NiniKo** [comment]
In fact, there is still one modification missing in the GUI to make it possible to change every month: the GUI does not allow a number beyond 10,000 minutes or 6 days 22 hours and 40 minutes. A little oversight I think 😉.

**Comment by Mamiglia** [comment]
I can't believe I forgot even this one, next commit should fix this
