### ISSUE TITLE
Restrictive Query Error

### ISSUE THREAD

**Issue by ghost** [Mamiglia/Reddit-Wallpaper#9]
Hello! Thank you for the great app. Works well, except, I previously had /r/earthporn and it worked great. But, now I am using an NSFW subreddit and I keep getting this error:

NOTE: I have replaced the name of the subreddit with NSFWquery... you can try any such sub-reddit to reproduce and test... 

```
INFO: Search Query is: https://reddit.com/search.json?q=subreddit:(NSFWquery)+self:no&sort=relevance&limit=50&t=all&type=t3&restrict_sr=true
WARNING: No new wallpaper is proposed, setting a recent wallpaper. Maybe your query is too restrictive?
INFO: Wallpapers is successfully set to:
title:	Colorful_sunset_over_Crystal_Lake_NW_Arkansas_OC4096x6144
image url:	https://i.redd.it/1jrd9tb2h3o71.jpg
post url:	https://www.reddit.com/r/EarthPorn/comments/pq44je/colorful_sunset_over_crystal_lake_nw_arkansas/
INFO: Sleep is interrupted
INFO: Search Query is: https://reddit.com/search.json?q=subreddit:(NSFWquery)+self:no&sort=relevance&limit=50&t=all&type=t3&restrict_sr=true
WARNING: No new wallpaper is proposed, setting a recent wallpaper. Maybe your query is too restrictive?
INFO: Wallpapers is successfully set to:
title:	Hoodoos_in_the_fog__Yellowstone_National_Park_WY_3840x2160__OC
image url:	https://i.redd.it/dtvib3fsj3o71.jpg
post url:	https://www.reddit.com/r/EarthPorn/comments/pq4esg/hoodoos_in_the_fog_yellowstone_national_park_wy/
```
Ultimately with the error, the app defaults to previous good sub-reddit (/r/earthporn) and it continues to pull and display the pics.

Thank you for looking into this.

**Comment by Mamiglia** [comment]
Hey, can you give me the name of the subreddit in question for... _research reasons_?
Jokes aside I do need an example subreddit of this kind, since I know no subreddit that posts NSFW content in at least 1920x1080

**Comment by Mamiglia** [comment]
I was looking into this, and it's strange! Look at this query for example: [link](https://www.reddit.com/search.json?q=subreddit:(hentaiwallpapers)+self:no&sort=hot&limit=3&t=day&type=t3&restrict_sr=true), if you open the link in your browser it works and finds results, BUT if you try it in an incognito window it won't work! I think that's because reddit requires you to identify as an over-18 adult before searching nsfw content for you. Now the question is how to circumvent this issue

**Comment by Mamiglia** [comment]
Solution found! I can just slap &include_over_18=true at the end of the query to obtain that. I'll include this in the [next commit](https://github.com/Mamiglia/Reddit-Wallpaper/commit/a0aad81958772b44408d6c534a6da85e3932b9f3)

**Comment by ghost** [comment]
... for... research reasons? HA HA ... LMAO! Good one!

You are right; there isn't a subreddit that posts NSFW stuff in 1920x1080. But, the program should pull stuff if it is less than 1920x1080, right? Not greater than 1920x1080 as that is the resolution of my monitor. 

Your query does not work in my browser (firefox with a bunch of privacy addons) nor did it work in incognito mode. Chromium with ublock_origin gave me this: 

{"kind": "Listing", "data": {"modhash": "", "dist": 0, "facets": {}, "after": null, "geo_filter": "", "children": [], "before": null}} 

as output!

I think you are on the right track with this. In another program, I have seen nsfw=yes somewhere. 

Ah... you solved it! Great! Look forward to it : )

Thank you!

**Comment by Mamiglia** [comment]
No, that's not the way the program works! It pulls stuff that has a resolution **above** 1920x1080! (you can change this value in the "Advanced" tab of the settings and set it to 1x1 to allow all images)

I mistyped the link above, the correct one that works normally but doesn't work on incognito is [this](https://www.reddit.com/search.json?q=subreddit:(hentai)+self:no&sort=hot&limit=50&t=day&type=t3&restrict_sr=true&nsfw=yes)

Anyway thanks for making me notice this issue!

I made this feature that will be in the next release, I think you might enjoy it:
![image](https://user-images.githubusercontent.com/33762284/134066772-540ab340-c7d1-4712-ab3b-138b6df0535b.png)

**Comment by ghost** [comment]
Okay, your explanation of image resolution makes better sense actually :) 

The link you provided did not work - in Firefox or chrome. I got similar error again. No worries, as long as you are able to test!

The feature looks good. Question: I understand NEVER and ALLOW but what does ONLY mean? ONLY NSFW images?

**Comment by Mamiglia** [comment]
YEAH

but it's not working so I may decide to temporarily cut it out

**Comment by ghost** [comment]
Tried the new "stabilizing" version -- works great! Thank you!
